import { Product, Batch, Category, Company, User, Supplier, Customer, Branch, Device, PharmacySettings, RolePermissions } from '../types/pharmacy';

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'branch-main-01',
    nameAr: 'الفرع الرئيسي - صيدلية الشفاء',
    address: 'شارع التحرير، الدقي، الجيزة',
    phone: '0233445566',
    isMain: true,
  },
  {
    id: 'branch-02',
    nameAr: 'فرع مدينة نصر',
    address: 'شارع عباس العقاد، مدينة نصر، القاهرة',
    phone: '0224011223',
    isMain: false,
  }
];

export const INITIAL_DEVICES: Device[] = [
  {
    id: 'DEV-WIN-01',
    name: 'كاشير 1 (كمبيوتر رئيسي / سيرفر محلي)',
    type: 'windows_pos',
    ip: '192.168.1.10',
    branchId: 'branch-main-01',
    lastSeen: 'الآن (متصل)',
    syncStatus: 'synced',
    status: 'active',
  },
  {
    id: 'DEV-AND-01',
    name: 'تابلت المخزن المحمول (Android)',
    type: 'android_mobile',
    ip: '192.168.1.25',
    branchId: 'branch-main-01',
    lastSeen: 'منذ دقيقة',
    syncStatus: 'synced',
    status: 'active',
  },
  {
    id: 'DEV-WIN-02',
    name: 'كاشير 2 (Windows POS)',
    type: 'windows_pos',
    ip: '192.168.1.15',
    branchId: 'branch-main-01',
    lastSeen: 'منذ 5 دقائق',
    syncStatus: 'synced',
    status: 'active',
  }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-01',
    name: 'د. أحمد محمود (مدير النظام)',
    username: 'admin',
    password: '123',
    role: 'admin',
    branchId: 'branch-main-01',
    deviceId: 'DEV-WIN-01',
    phone: '01012345678',
    status: 'active',
    createdAt: '2025-01-01',
  },
  {
    id: 'usr-mgr-01',
    name: 'د. سارة عادل (مديرة الصيدلية)',
    username: 'manager',
    password: '123',
    role: 'manager',
    branchId: 'branch-main-01',
    deviceId: 'DEV-WIN-01',
    phone: '01198765432',
    status: 'active',
    createdAt: '2025-01-15',
  },
  {
    id: 'usr-csh-01',
    name: 'محمود كمال (كاشير صيدلي)',
    username: 'cashier',
    password: '123',
    role: 'cashier',
    branchId: 'branch-main-01',
    deviceId: 'DEV-WIN-01',
    phone: '01234567890',
    status: 'active',
    createdAt: '2025-02-01',
  },
];

export const INITIAL_PERMISSIONS: RolePermissions[] = [
  {
    role: 'admin',
    permissions: [
      'pos.sell', 'pos.discount', 'pos.change_price', 'pos.hold', 'pos.return',
      'products.view', 'products.create', 'products.edit', 'products.delete',
      'inventory.view', 'inventory.adjust', 'inventory.transfer',
      'purchases.view', 'purchases.create',
      'reports.sales', 'reports.profit', 'reports.inventory', 'reports.expiry',
      'customers.manage', 'suppliers.manage', 'expenses.manage',
      'users.manage', 'settings.manage', 'backup.manage', 'audit.view'
    ]
  },
  {
    role: 'manager',
    permissions: [
      'pos.sell', 'pos.discount', 'pos.hold', 'pos.return',
      'products.view', 'products.create', 'products.edit',
      'inventory.view', 'inventory.adjust', 'inventory.transfer',
      'purchases.view', 'purchases.create',
      'reports.sales', 'reports.inventory', 'reports.expiry',
      'customers.manage', 'suppliers.manage', 'expenses.manage',
      'audit.view'
    ]
  },
  {
    role: 'cashier',
    permissions: [
      'pos.sell', 'pos.hold', 'pos.return',
      'products.view',
      'customers.manage'
    ]
  }
];

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', nameAr: 'مسكنات ومضادات التهاب', description: 'أدوية علاج الآلام وخافضات الحرارة' },
  { id: 'cat-2', nameAr: 'مضادات حيوية', description: 'مضادات البكتيريا والميكروبات' },
  { id: 'cat-3', nameAr: 'أدوية القلب والضغط', description: 'منظمات ضغط الدم والقلب' },
  { id: 'cat-4', nameAr: 'أدوية السكري', description: 'خافضات سكر الدم وأنسولين' },
  { id: 'cat-5', nameAr: 'الجهاز الهضمي والمعدة', description: 'مضادات الحموضة والمطهرات المعوية' },
  { id: 'cat-6', nameAr: 'فيتامينات ومكملات غذائية', description: 'المعادن والفيتامينات والمقويات' },
  { id: 'cat-7', nameAr: 'أدوية الحساسية والجهاز التنفسي', description: 'موسعات الشعب ومضادات الهيستامين' },
  { id: 'cat-8', nameAr: 'عناية شخصية ومستلزمات', description: 'مستلزمات طبية وضمادات وشاش' }
];

export const INITIAL_COMPANIES: Company[] = [
  { id: 'cmp-1', nameAr: 'Novartis (نوفارتس)', country: 'سويسرا' },
  { id: 'cmp-2', nameAr: 'GlaxoSmithKline (GSK)', country: 'بريطانيا' },
  { id: 'cmp-3', nameAr: 'Sanofi (سانوفي)', country: 'فرنسا' },
  { id: 'cmp-4', nameAr: 'Eva Pharma (إيفا فارما)', country: 'مصر' },
  { id: 'cmp-5', nameAr: 'Amoun Pharmaceuticals (آمون)', country: 'مصر' },
  { id: 'cmp-6', nameAr: 'Pfizer (فايزر)', country: 'الولايات المتحدة' },
  { id: 'cmp-7', nameAr: 'EIPICO (إيبيكو)', country: 'مصر' },
  { id: 'cmp-8', nameAr: 'Pharco (فاركو)', country: 'مصر' }
];

// Reference date for calculations: today is 2026-09-08
export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    nameAr: 'بنادول إكسترا 24 قرص',
    nameEn: 'Panadol Extra 24 Tabs',
    barcode: '6221000100018',
    additionalBarcodes: ['5000347070549'],
    internalCode: 'MED-1001',
    sku: 'PAN-EXT-24',
    categoryId: 'cat-1',
    companyId: 'cmp-2',
    activeIngredient: 'Paracetamol 500mg + Caffeine 65mg',
    unit: 'علبة (2 شريط)',
    purchasePrice: 38.00,
    salePrice: 48.00,
    minimumStock: 15,
    tax: 0,
    description: 'مسكن قوي لآلام الصداع والأسنان وخافض للحرارة',
    status: 'active',
    requiresPrescription: false,
    createdAt: '2025-01-10',
    updatedAt: '2026-08-01',
  },
  {
    id: 'prod-002',
    nameAr: 'كونكور 5 مجم 30 قرص',
    nameEn: 'Concor 5mg 30 Tabs',
    barcode: '6221000100025',
    additionalBarcodes: [],
    internalCode: 'MED-1002',
    sku: 'CON-05-30',
    categoryId: 'cat-3',
    companyId: 'cmp-1',
    activeIngredient: 'Bisoprolol Fumarate 5mg',
    unit: 'علبة (3 شرائط)',
    purchasePrice: 72.00,
    salePrice: 90.00,
    minimumStock: 10,
    tax: 0,
    description: 'علاج ارتفاع ضغط الدم والذبحة الصدرية وتنظيم ضربات القلب',
    status: 'active',
    requiresPrescription: true,
    createdAt: '2025-01-12',
    updatedAt: '2026-08-10',
  },
  {
    id: 'prod-003',
    nameAr: 'أوجمنتين 1 جم 14 قرص',
    nameEn: 'Augmentin 1g 14 Tabs',
    barcode: '6221000100032',
    additionalBarcodes: ['5000347060120'],
    internalCode: 'MED-1003',
    sku: 'AUG-1G-14',
    categoryId: 'cat-2',
    companyId: 'cmp-2',
    activeIngredient: 'Amoxicillin 875mg + Clavulanic Acid 125mg',
    unit: 'علبة (2 شريط)',
    purchasePrice: 110.00,
    salePrice: 135.00,
    minimumStock: 20,
    tax: 0,
    description: 'مضاد حيوي واسع المجال لالتهابات الجهاز التنفسي والمسالك البولية',
    status: 'active',
    requiresPrescription: true,
    createdAt: '2025-01-15',
    updatedAt: '2026-08-15',
  },
  {
    id: 'prod-004',
    nameAr: 'كيتوفان 75 مجم 30 كبسولة',
    nameEn: 'Ketofan 75mg 30 Caps',
    barcode: '6221000100049',
    additionalBarcodes: [],
    internalCode: 'MED-1004',
    sku: 'KET-75-30',
    categoryId: 'cat-1',
    companyId: 'cmp-5',
    activeIngredient: 'Ketoprofen 75mg',
    unit: 'علبة (3 شرائط)',
    purchasePrice: 28.00,
    salePrice: 36.00,
    minimumStock: 12,
    tax: 0,
    description: 'مسكن ومضاد لالتهاب المفاصل والعظام وآلام العمود الفقري',
    status: 'active',
    requiresPrescription: false,
    createdAt: '2025-02-01',
    updatedAt: '2026-08-20',
  },
  {
    id: 'prod-005',
    nameAr: 'أنتينال 24 كبسولة',
    nameEn: 'Antinal 24 Caps',
    barcode: '6221000100056',
    additionalBarcodes: [],
    internalCode: 'MED-1005',
    sku: 'ANT-24-CAP',
    categoryId: 'cat-5',
    companyId: 'cmp-5',
    activeIngredient: 'Nifuroxazide 200mg',
    unit: 'علبة (2 شريط)',
    purchasePrice: 32.00,
    salePrice: 42.00,
    minimumStock: 15,
    tax: 0,
    description: 'مطهر معوي واسع المدى لعلاج النزلات المعوية والإسهال البكتيري',
    status: 'active',
    requiresPrescription: false,
    createdAt: '2025-02-10',
    updatedAt: '2026-08-22',
  },
  {
    id: 'prod-006',
    nameAr: 'سيتال 500 مجم 20 قرص',
    nameEn: 'Cetal 500mg 20 Tabs',
    barcode: '6221000100063',
    additionalBarcodes: [],
    internalCode: 'MED-1006',
    sku: 'CET-500-20',
    categoryId: 'cat-1',
    companyId: 'cmp-7',
    activeIngredient: 'Paracetamol 500mg',
    unit: 'علبة (2 شريط)',
    purchasePrice: 14.00,
    salePrice: 19.50,
    minimumStock: 25,
    tax: 0,
    description: 'خافض للحرارة ومسكن آمن للأطفال والحوامل وكبار السن',
    status: 'active',
    requiresPrescription: false,
    createdAt: '2025-02-15',
    updatedAt: '2026-08-25',
  },
  {
    id: 'prod-007',
    nameAr: 'تلفاست 120 مجم 20 قرص',
    nameEn: 'Telfast 120mg 20 Tabs',
    barcode: '6221000100070',
    additionalBarcodes: [],
    internalCode: 'MED-1007',
    sku: 'TEL-120-20',
    categoryId: 'cat-7',
    companyId: 'cmp-3',
    activeIngredient: 'Fexofenadine Hydrochloride 120mg',
    unit: 'علبة (2 شريط)',
    purchasePrice: 65.00,
    salePrice: 82.00,
    minimumStock: 8,
    tax: 0,
    description: 'مضاد للحساسية والرشح وحساسية الجلد والجيوب الأنفية بدون نعاس',
    status: 'active',
    requiresPrescription: false,
    createdAt: '2025-03-01',
    updatedAt: '2026-08-28',
  },
  {
    id: 'prod-008',
    nameAr: 'جلوكوفاج 1000 مجم 30 قرص',
    nameEn: 'Glucophage 1000mg 30 Tabs',
    barcode: '6221000100087',
    additionalBarcodes: [],
    internalCode: 'MED-1008',
    sku: 'GLU-1000-30',
    categoryId: 'cat-4',
    companyId: 'cmp-4',
    activeIngredient: 'Metformin Hydrochloride 1000mg',
    unit: 'علبة (3 شرائط)',
    purchasePrice: 45.00,
    salePrice: 60.00,
    minimumStock: 15,
    tax: 0,
    description: 'علاج مرض السكري من النوع الثاني وتحسين حساسية الأنسولين',
    status: 'active',
    requiresPrescription: true,
    createdAt: '2025-03-05',
    updatedAt: '2026-08-29',
  },
  {
    id: 'prod-009',
    nameAr: 'أوميجا 3 بلس 30 كبسولة',
    nameEn: 'Omega 3 Plus 30 Caps',
    barcode: '6221000100094',
    additionalBarcodes: [],
    internalCode: 'MED-1009',
    sku: 'OMG-3-30',
    categoryId: 'cat-6',
    companyId: 'cmp-5',
    activeIngredient: 'Fish Oil 1000mg + Wheat Germ Oil 100mg',
    unit: 'علبة (3 شرائط)',
    purchasePrice: 58.00,
    salePrice: 75.00,
    minimumStock: 10,
    tax: 0,
    description: 'مكمل غذائي لدعم صحة القلب والدماغ وتقليل الكوليسترول الضار',
    status: 'active',
    requiresPrescription: false,
    createdAt: '2025-03-10',
    updatedAt: '2026-09-01',
  },
  {
    id: 'prod-010',
    nameAr: 'أوميباك 20 مجم 14 كبسولة',
    nameEn: 'Omepak 20mg 14 Caps',
    barcode: '6221000100100',
    additionalBarcodes: [],
    internalCode: 'MED-1010',
    sku: 'OME-20-14',
    categoryId: 'cat-5',
    companyId: 'cmp-4',
    activeIngredient: 'Omeprazole 20mg',
    unit: 'علبة (2 شريط)',
    purchasePrice: 30.00,
    salePrice: 39.00,
    minimumStock: 8,
    tax: 0,
    description: 'علاج قرحة المعدة وارتجاع المريء وحموضة المعدة المزمنة',
    status: 'active',
    requiresPrescription: false,
    createdAt: '2025-03-15',
    updatedAt: '2026-09-02',
  },
  {
    id: 'prod-011',
    nameAr: 'كحول إيثيلي 70% بخاخ 250 مل',
    nameEn: 'Ethyl Alcohol 70% Spray 250ml',
    barcode: '6221000100117',
    additionalBarcodes: [],
    internalCode: 'MED-1011',
    sku: 'ALC-70-250',
    categoryId: 'cat-8',
    companyId: 'cmp-8',
    activeIngredient: 'Ethanol 70%',
    unit: 'عبوة',
    purchasePrice: 18.00,
    salePrice: 25.00,
    minimumStock: 20,
    tax: 14,
    description: 'مظهر ومعقم طبي لليدين والأسطح',
    status: 'active',
    requiresPrescription: false,
    createdAt: '2025-03-20',
    updatedAt: '2026-09-03',
  },
  {
    id: 'prod-012',
    nameAr: 'بروفين 400 مجم 30 قرص',
    nameEn: 'Brufen 400mg 30 Tabs',
    barcode: '6221000100124',
    additionalBarcodes: [],
    internalCode: 'MED-1012',
    sku: 'BRU-400-30',
    categoryId: 'cat-1',
    companyId: 'cmp-6',
    activeIngredient: 'Ibuprofen 400mg',
    unit: 'علبة (3 شرائط)',
    purchasePrice: 39.00,
    salePrice: 51.00,
    minimumStock: 10,
    tax: 0,
    description: 'مسكن ومضاد للالتهابات وخافض للحرارة',
    status: 'active',
    requiresPrescription: false,
    createdAt: '2025-04-01',
    updatedAt: '2026-09-04',
  }
];

// Batches with realistic expiry dates relative to current date (2026-09-08)
export const INITIAL_BATCHES: Batch[] = [
  // Panadol Extra (2 batches: one normal, one high quantity)
  {
    id: 'batch-001',
    productId: 'prod-001',
    batchNumber: 'B-PAN-2025A',
    expiryDate: '2027-11-30',
    purchasePrice: 38.00,
    salePrice: 48.00,
    quantity: 45,
    createdAt: '2025-01-10',
  },
  {
    id: 'batch-002',
    productId: 'prod-001',
    batchNumber: 'B-PAN-2026B',
    expiryDate: '2028-05-15',
    purchasePrice: 38.00,
    salePrice: 48.00,
    quantity: 30,
    createdAt: '2026-02-15',
  },
  // Concor 5mg (2 batches: one expiring soon in 20 days: 2026-09-28!)
  {
    id: 'batch-003',
    productId: 'prod-002',
    batchNumber: 'B-CON-2024E',
    expiryDate: '2026-09-28', // Expires within 20 days!
    purchasePrice: 72.00,
    salePrice: 90.00,
    quantity: 6,
    createdAt: '2025-01-12',
  },
  {
    id: 'batch-004',
    productId: 'prod-002',
    batchNumber: 'B-CON-2026A',
    expiryDate: '2027-08-30',
    purchasePrice: 72.00,
    salePrice: 90.00,
    quantity: 24,
    createdAt: '2026-01-10',
  },
  // Augmentin 1g (Batch safe)
  {
    id: 'batch-005',
    productId: 'prod-003',
    batchNumber: 'B-AUG-991A',
    expiryDate: '2027-06-30',
    purchasePrice: 110.00,
    salePrice: 135.00,
    quantity: 22,
    createdAt: '2025-01-15',
  },
  // Ketofan 75mg (Batch expiring in 60 days: 2026-11-05)
  {
    id: 'batch-006',
    productId: 'prod-004',
    batchNumber: 'B-KET-041B',
    expiryDate: '2026-11-05', // Expires within 60 days
    purchasePrice: 28.00,
    salePrice: 36.00,
    quantity: 18,
    createdAt: '2025-02-01',
  },
  // Antinal (Low stock batch: only 4 left, minStock is 15!)
  {
    id: 'batch-007',
    productId: 'prod-005',
    batchNumber: 'B-ANT-781A',
    expiryDate: '2027-10-15',
    purchasePrice: 32.00,
    salePrice: 42.00,
    quantity: 4, // LOW STOCK!
    createdAt: '2025-02-10',
  },
  // Cetal (Safe batch)
  {
    id: 'batch-008',
    productId: 'prod-006',
    batchNumber: 'B-CET-112C',
    expiryDate: '2028-01-20',
    purchasePrice: 14.00,
    salePrice: 19.50,
    quantity: 60,
    createdAt: '2025-02-15',
  },
  // Telfast 120mg (Expired batch for testing discard/return: expired on 2026-08-15)
  {
    id: 'batch-009',
    productId: 'prod-007',
    batchNumber: 'B-TEL-EXPIRED',
    expiryDate: '2026-08-15', // EXPIRED!
    purchasePrice: 65.00,
    salePrice: 82.00,
    quantity: 3, // Expired quantity
    createdAt: '2025-03-01',
  },
  {
    id: 'batch-010',
    productId: 'prod-007',
    batchNumber: 'B-TEL-2027A',
    expiryDate: '2027-12-10',
    purchasePrice: 65.00,
    salePrice: 82.00,
    quantity: 15,
    createdAt: '2026-01-20',
  },
  // Glucophage 1000mg
  {
    id: 'batch-011',
    productId: 'prod-008',
    batchNumber: 'B-GLU-902A',
    expiryDate: '2027-09-30',
    purchasePrice: 45.00,
    salePrice: 60.00,
    quantity: 28,
    createdAt: '2025-03-05',
  },
  // Omega 3 Plus (Low stock: 5 units left, minStock 10!)
  {
    id: 'batch-012',
    productId: 'prod-009',
    batchNumber: 'B-OMG-332D',
    expiryDate: '2027-04-10',
    purchasePrice: 58.00,
    salePrice: 75.00,
    quantity: 5, // LOW STOCK!
    createdAt: '2025-03-10',
  },
  // Omepak 20mg
  {
    id: 'batch-013',
    productId: 'prod-010',
    batchNumber: 'B-OME-441A',
    expiryDate: '2027-07-25',
    purchasePrice: 30.00,
    salePrice: 39.00,
    quantity: 14,
    createdAt: '2025-03-15',
  },
  // Ethyl Alcohol 70%
  {
    id: 'batch-014',
    productId: 'prod-011',
    batchNumber: 'B-ALC-770K',
    expiryDate: '2028-12-31',
    purchasePrice: 18.00,
    salePrice: 25.00,
    quantity: 35,
    createdAt: '2025-03-20',
  },
  // Brufen 400mg
  {
    id: 'batch-015',
    productId: 'prod-012',
    batchNumber: 'B-BRU-552A',
    expiryDate: '2027-11-15',
    purchasePrice: 39.00,
    salePrice: 51.00,
    quantity: 25,
    createdAt: '2025-04-01',
  }
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-001',
    name: 'الشركة المتحدة للتوزيع الدوائي',
    phone: '01001122334',
    address: 'مدينة العبور، المنطقة الصناعية، بلوك 12',
    notes: 'موزع رئيسي لمنتجات نوفارتس وجلاكسو وسانوفي - خصم نقدي 3%',
    balance: 14500.00, // We owe them 14,500 EGP
    createdAt: '2025-01-05',
  },
  {
    id: 'sup-002',
    name: 'شركة ابن سينا فارما',
    phone: '01122334455',
    address: 'المهندسين، شارع مصدق، الجيزة',
    notes: 'توصيل يومي مرتين - أدوية محلية ومستوردة',
    balance: 8200.00,
    createdAt: '2025-01-10',
  },
  {
    id: 'sup-003',
    name: 'فارما أوفرسيز للتجارة والتوزيع',
    phone: '01233445566',
    address: 'مدينة نصر، الحي السابع، القاهرة',
    notes: 'موزع إيفا وآمون وإيبيكو',
    balance: 0.00,
    createdAt: '2025-02-01',
  }
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-001',
    name: 'عميل نقدي عام (بدون اسم)',
    phone: '-',
    address: '-',
    notes: 'عملاء الصيدلية العابرين',
    balance: 0.00,
    createdAt: '2025-01-01',
  },
  {
    id: 'cust-002',
    name: 'أ/ سامي عبد الرحمن',
    phone: '01065432109',
    address: 'الدقي، شارع مصدق، عمارة 14',
    notes: 'عميل منتظم - مريض ضغط وسكر مزمن - حساب شهري',
    balance: 380.00, // owes us 380 EGP
    createdAt: '2025-01-15',
  },
  {
    id: 'cust-003',
    name: 'د/ منى الشافعي',
    phone: '01145678901',
    address: 'الدقي، برج الأطباء',
    notes: 'عيادة أطفال مجاورة - طلبات طوارئ',
    balance: 0.00,
    createdAt: '2025-02-10',
  },
  {
    id: 'cust-004',
    name: 'م/ طارق إبراهيم',
    phone: '01298765432',
    address: 'شارع السودان، المهندسين',
    notes: 'عميل آجل',
    balance: 145.00,
    createdAt: '2025-03-01',
  }
];

export const INITIAL_SETTINGS: PharmacySettings = {
  pharmacyNameAr: 'صيدلية الشفاء التخصصية',
  pharmacyNameEn: 'Al-Shefa Specialized Pharmacy',
  taxNumber: 'EG-984-210-765',
  commercialRegister: 'CR-104822',
  phone1: '02-33445566',
  phone2: '010-12345678',
  address: 'شارع التحرير، الدقي، الجيزة، مصر',
  currency: 'ج.م',
  taxRate: 0, // In Egypt, most medicines are exempt from VAT, non-meds have 14%
  invoiceFooterMessage: 'نتمنى لكم دوام الصحة والعافية - نسعد بخدمتكم دائماً',
  enableSoundAlerts: true,
  defaultPrinterType: 'thermal',
  thermalWidth: '80mm',
  barcodeLabelWidth: 50,
  barcodeLabelHeight: 25,
  autoSyncIntervalMinutes: 5,
  serverIp: '192.168.1.10',
  serverPort: 5000,
  networkMode: 'local_lan',
  requirePrescriptionWarning: true,
};
